<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" ng-app="pingApp">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

	<title>WebPing</title>

	<!-- Bootstrap core CSS -->
	<?php echo $this->headLink()->appendStylesheet('/css/bootstrap/bootstrap.css') ?>

	<!-- Custom styles for this template -->
	<?php echo $this->headLink()->appendStylesheet('/css/bootstrap/sticky-footer-navbar.css') ?>

</head>

<body>

<!-- Wrap all page content here -->
<div id="wrap">

	<!-- Fixed navbar -->
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
		</div>
	</div>

	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>Web Ping</h1>
		</div>

			<?php echo $this->layout()->content ?>

	</div>
</div>

<div id="footer">
	<div class="container">
		<p class="text-muted credit">Example courtesy <a href="http://martinbean.co.uk">Martin Bean</a> and <a href="http://ryanfait.com/sticky-footer/">Ryan Fait</a>.</p>
	</div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/angularjs/angularjs-1.0.8.min.js"></script>
<script src="/js/angularjs/ui-bootstrap-custom-tpls-0.6.0.js"></script>
<script src="/js/angularjs-app/app.js"></script>
<script src="/js/angularjs-app/controllers/MainController.js"></script>
<script src="/js/angularjs-app/factory/HostFactory.js"></script>

</body>
</html>
